name: jobportal
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  device_preview: ^1.2.0
  iconsax: ^0.0.8
  intl: ^0.19.0
  dotted_border: ^3.1.0
  share_plus: ^12.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  dio: ^5.9.0
  retrofit: ^4.6.0
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.7.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5


flutter:


  uses-material-design: true

  assets:
      - assets/icons/google.png
      - assets/images/onboard.png
      - assets/images/logo.png
      - assets/images/otp.png
      - assets/images/
      - assets/icons/
      - assets/fonts/dmsans/



  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/dmsans/DMSans-Regular.ttf
        - asset: assets/fonts/dmsans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dmsans/DMSans-Bold.ttf
          weight: 700
